=begin
#The Plaid API

#The Plaid REST API. Please see https://plaid.com/docs/api for more details.

The version of the OpenAPI document: 2020-09-14_1.64.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'date'
require 'time'

module OpenapiClient
  class VerificationRefreshStatus
    STATUS_USER_PRESENCE_REQUIRED = "VERIFICATION_REFRESH_STATUS_USER_PRESENCE_REQUIRED".freeze
    SUCCESSFUL = "VERIFICATION_REFRESH_SUCCESSFUL".freeze
    NOT_FOUND = "VERIFICATION_REFRESH_NOT_FOUND".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = VerificationRefreshStatus.constants.select { |c| VerificationRefreshStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #VerificationRefreshStatus" if constantValues.empty?
      value
    end
  end
end
