=begin
#The Plaid API

#The Plaid REST API. Please see https://plaid.com/docs/api for more details.

The version of the OpenAPI document: 2020-09-14_1.64.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::IncomeVerificationPrecheckMilitaryInfo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::IncomeVerificationPrecheckMilitaryInfo do
  let(:instance) { OpenapiClient::IncomeVerificationPrecheckMilitaryInfo.new }

  describe 'test an instance of IncomeVerificationPrecheckMilitaryInfo' do
    it 'should create an instance of IncomeVerificationPrecheckMilitaryInfo' do
      expect(instance).to be_instance_of(OpenapiClient::IncomeVerificationPrecheckMilitaryInfo)
    end
  end
  describe 'test attribute "is_active_duty"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "branch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["AIR FORCE", "ARMY", "COAST GUARD", "MARINES", "NAVY", "UNKNOWN"])
      # validator.allowable_values.each do |value|
      #   expect { instance.branch = value }.not_to raise_error
      # end
    end
  end

end
