=begin
#The Plaid API

#The Plaid REST API. Please see https://plaid.com/docs/api for more details.

The version of the OpenAPI document: 2020-09-14_1.64.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ProcessorTokenCreateRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ProcessorTokenCreateRequest do
  let(:instance) { OpenapiClient::ProcessorTokenCreateRequest.new }

  describe 'test an instance of ProcessorTokenCreateRequest' do
    it 'should create an instance of ProcessorTokenCreateRequest' do
      expect(instance).to be_instance_of(OpenapiClient::ProcessorTokenCreateRequest)
    end
  end
  describe 'test attribute "client_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "secret"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "access_token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "account_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "processor"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["achq", "alpaca", "astra", "check", "checkbook", "circle", "drivewealth", "dwolla", "galileo", "lithic", "modern_treasury", "moov", "ocrolus", "prime_trust", "rize", "sila_money", "svb_api", "treasury_prime", "unit", "vesta", "vopay", "wyre"])
      # validator.allowable_values.each do |value|
      #   expect { instance.processor = value }.not_to raise_error
      # end
    end
  end

end
