=begin
#The Plaid API

#The Plaid REST API. Please see https://plaid.com/docs/api for more details.

The version of the OpenAPI document: 2020-09-14_1.64.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SandboxItemFireWebhookRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SandboxItemFireWebhookRequest do
  let(:instance) { OpenapiClient::SandboxItemFireWebhookRequest.new }

  describe 'test an instance of SandboxItemFireWebhookRequest' do
    it 'should create an instance of SandboxItemFireWebhookRequest' do
      expect(instance).to be_instance_of(OpenapiClient::SandboxItemFireWebhookRequest)
    end
  end
  describe 'test attribute "client_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "secret"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "access_token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "webhook_code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["DEFAULT_UPDATE", "NEW_ACCOUNTS_AVAILABLE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.webhook_code = value }.not_to raise_error
      # end
    end
  end

end
