=begin
#The Plaid API

#The Plaid REST API. Please see https://plaid.com/docs/api for more details.

The version of the OpenAPI document: 2020-09-14_1.64.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::VerificationAttribute
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::VerificationAttribute do
  let(:instance) { OpenapiClient::VerificationAttribute.new }

  describe 'test an instance of VerificationAttribute' do
    it 'should create an instance of VerificationAttribute' do
      expect(instance).to be_instance_of(OpenapiClient::VerificationAttribute)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["VERIFICATION_ATTRIBUTE_TYPE_UNKNOWN", "VERIFICATION_ATTRIBUTE_TYPE_AMOUNT_MATCH", "VERIFICATION_ATTRIBUTE_TYPE_DATE_MATCH", "VERIFICATION_ATTRIBUTE_TYPE_DATE_MISMATCH", "VERIFICATION_ATTRIBUTE_TYPE_FILE_TAMPERING", "VERIFICATION_ATTRIBUTE_TYPE_DESCRIPTION_MATCH", "VERIFICATION_ATTRIBUTE_TYPE_DESCRIPTION_MISMATCH", "VERIFICATION_ATTRIBUTE_TYPE_FIRST_NAME_MATCH", "VERIFICATION_ATTRIBUTE_TYPE_FIRST_NAME_MISMATCH", "VERIFICATION_ATTRIBUTE_TYPE_LAST_NAME_MATCH", "VERIFICATION_ATTRIBUTE_TYPE_LAST_NAME_MISMATCH", "null"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

end
